replicaCount: 5
image:
  repository: tvieirabruna/nlw.service.passin
  pullPolicy: Always
  tag: 18a9505
  port: 3333
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 8
  targetMemoryUtilizationPercentage: 75
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
configMap:
  name: nlw-env
  url: http://localhost:3333
secret:
  name: db-connection
  type: Opaque
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19ic3F4WUxrMXc1bzlDNjFvTnl0QG5sdy11bml0ZS1kby11c2VyLTE2MjM4NjkwLTAuYy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvbmx3LXVuaXRlP3NzbG1vZGU9cmVxdWlyZQ==
envDatabase: DATABASE_URL
envAPI: API_BASE_URL
